# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'JTComponentKit', :path => '../'
  pod 'Masonry'
  pod 'SnapKit'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'JTComponentKit', :path => '../'
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            end
        end
    end
end
